### ISSUE TITLE
unable to compile on MacOS with gcc 4.91

### ISSUE THREAD

**Issue by huananfshi** [TulsaBioinformaticsToolsmith/MeShClust2#8]
```/Users/huananshi/MeShClust2/src/clutil/Loader.cpp: In instantiation of ‘std::vector<Point<T>*> Loader<T>::load_next(int) [with T = double]’:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:218:16:   required from here
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: error: no matching function for call to ‘Loader<double>::get_point(std::basic_string<char>&, std::basic_string<char>&, __gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type&, int&)’
   Point<T>* p = get_point(pr.first, *pr.second, id_list.at(tid), k);
                                                                   ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: note: candidates are:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note: static Point<T>* Loader<T>::get_point(std::string, const string&, uintmax_t&, int, bool) [with T = double; std::string = std::basic_string<char>; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(std::string header, const std::string &base, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note:   no known conversion for argument 3 from ‘__gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type {aka long long unsigned int}’ to ‘uintmax_t& {aka long unsigned int&}’
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note: static Point<T>* Loader<T>::get_point(nonltr::ChromosomeOneDigit*, uintmax_t&, int, bool) [with T = double; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(ChromosomeOneDigit* chrom, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note:   no known conversion for argument 1 from ‘std::basic_string<char>’ to ‘nonltr::ChromosomeOneDigit*’
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp: In instantiation of ‘std::vector<Point<T>*> Loader<T>::load_next(int) [with T = int]’:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:219:16:   required from here
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: error: no matching function for call to ‘Loader<int>::get_point(std::basic_string<char>&, std::basic_string<char>&, __gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type&, int&)’
   Point<T>* p = get_point(pr.first, *pr.second, id_list.at(tid), k);
                                                                   ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: note: candidates are:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note: static Point<T>* Loader<T>::get_point(std::string, const string&, uintmax_t&, int, bool) [with T = int; std::string = std::basic_string<char>; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(std::string header, const std::string &base, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note:   no known conversion for argument 3 from ‘__gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type {aka long long unsigned int}’ to ‘uintmax_t& {aka long unsigned int&}’
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note: static Point<T>* Loader<T>::get_point(nonltr::ChromosomeOneDigit*, uintmax_t&, int, bool) [with T = int; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(ChromosomeOneDigit* chrom, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note:   no known conversion for argument 1 from ‘std::basic_string<char>’ to ‘nonltr::ChromosomeOneDigit*’
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp: In instantiation of ‘std::vector<Point<T>*> Loader<T>::load_next(int) [with T = long long unsigned int]’:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:220:16:   required from here
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: error: no matching function for call to ‘Loader<long long unsigned int>::get_point(std::basic_string<char>&, std::basic_string<char>&, __gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type&, int&)’
   Point<T>* p = get_point(pr.first, *pr.second, id_list.at(tid), k);
                                                                   ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: note: candidates are:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note: static Point<T>* Loader<T>::get_point(std::string, const string&, uintmax_t&, int, bool) [with T = long long unsigned int; std::string = std::basic_string<char>; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(std::string header, const std::string &base, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note:   no known conversion for argument 3 from ‘__gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type {aka long long unsigned int}’ to ‘uintmax_t& {aka long unsigned int&}’
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note: static Point<T>* Loader<T>::get_point(nonltr::ChromosomeOneDigit*, uintmax_t&, int, bool) [with T = long long unsigned int; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(ChromosomeOneDigit* chrom, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note:   no known conversion for argument 1 from ‘std::basic_string<char>’ to ‘nonltr::ChromosomeOneDigit*’
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp: In instantiation of ‘std::vector<Point<T>*> Loader<T>::load_next(int) [with T = unsigned int]’:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:221:16:   required from here
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: error: no matching function for call to ‘Loader<unsigned int>::get_point(std::basic_string<char>&, std::basic_string<char>&, __gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type&, int&)’
   Point<T>* p = get_point(pr.first, *pr.second, id_list.at(tid), k);
                                                                   ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: note: candidates are:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note: static Point<T>* Loader<T>::get_point(std::string, const string&, uintmax_t&, int, bool) [with T = unsigned int; std::string = std::basic_string<char>; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(std::string header, const std::string &base, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note:   no known conversion for argument 3 from ‘__gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type {aka long long unsigned int}’ to ‘uintmax_t& {aka long unsigned int&}’
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note: static Point<T>* Loader<T>::get_point(nonltr::ChromosomeOneDigit*, uintmax_t&, int, bool) [with T = unsigned int; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(ChromosomeOneDigit* chrom, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note:   no known conversion for argument 1 from ‘std::basic_string<char>’ to ‘nonltr::ChromosomeOneDigit*’
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp: In instantiation of ‘std::vector<Point<T>*> Loader<T>::load_next(int) [with T = short unsigned int]’:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:222:16:   required from here
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: error: no matching function for call to ‘Loader<short unsigned int>::get_point(std::basic_string<char>&, std::basic_string<char>&, __gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type&, int&)’
   Point<T>* p = get_point(pr.first, *pr.second, id_list.at(tid), k);
                                                                   ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: note: candidates are:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note: static Point<T>* Loader<T>::get_point(std::string, const string&, uintmax_t&, int, bool) [with T = short unsigned int; std::string = std::basic_string<char>; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(std::string header, const std::string &base, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note:   no known conversion for argument 3 from ‘__gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type {aka long long unsigned int}’ to ‘uintmax_t& {aka long unsigned int&}’
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note: static Point<T>* Loader<T>::get_point(nonltr::ChromosomeOneDigit*, uintmax_t&, int, bool) [with T = short unsigned int; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(ChromosomeOneDigit* chrom, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note:   no known conversion for argument 1 from ‘std::basic_string<char>’ to ‘nonltr::ChromosomeOneDigit*’
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp: In instantiation of ‘std::vector<Point<T>*> Loader<T>::load_next(int) [with T = unsigned char]’:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:223:16:   required from here
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: error: no matching function for call to ‘Loader<unsigned char>::get_point(std::basic_string<char>&, std::basic_string<char>&, __gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type&, int&)’
   Point<T>* p = get_point(pr.first, *pr.second, id_list.at(tid), k);
                                                                   ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:193:67: note: candidates are:
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note: static Point<T>* Loader<T>::get_point(std::string, const string&, uintmax_t&, int, bool) [with T = unsigned char; std::string = std::basic_string<char>; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(std::string header, const std::string &base, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:112:11: note:   no known conversion for argument 3 from ‘__gnu_cxx::__alloc_traits<std::allocator<long long unsigned int> >::value_type {aka long long unsigned int}’ to ‘uintmax_t& {aka long unsigned int&}’
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note: static Point<T>* Loader<T>::get_point(nonltr::ChromosomeOneDigit*, uintmax_t&, int, bool) [with T = unsigned char; uintmax_t = long unsigned int]
 Point<T>* Loader<T>::get_point(ChromosomeOneDigit* chrom, uintmax_t& id, int k, bool set_seq)
           ^
/Users/huananshi/MeShClust2/src/clutil/Loader.cpp:138:11: note:   no known conversion for argument 1 from ‘std::basic_string<char>’ to ‘nonltr::ChromosomeOneDigit*’
make[2]: *** [CMakeFiles/ClusterUtil.dir/src/clutil/Loader.cpp.o] Error 1
make[1]: *** [CMakeFiles/ClusterUtil.dir/all] Error 2
make: *** [all] Error 2```

**Comment by hani-girgis** [comment]
The newest version of MeShClust (v3.0) can be obtained from https://github.com/BioinformaticsToolsmith/Identity.git

Let us know if you have any questions.
